# Generated by Django 3.2.5 on 2021-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer_Details', '0002_alter_farmer_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='img_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='taluka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=50),
        ),
    ]
