# Generated by Django 3.2.5 on 2021-07-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer_Details', '0003_auto_20210709_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer_Details.district'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer_Details.taluka'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer_Details.village'),
        ),
    ]
